export const pagesEditorTheme = {
    wrapper: 'flex flex-col h-full min-h-0',
    toolbar: 'flex items-center gap-2 flex-wrap px-4 py-3 border-b border-gray-100 bg-white flex-shrink-0',
    lensBar: 'flex items-center gap-1.5 flex-wrap',
    lensChip: 'inline-flex items-center gap-1.5 border border-gray-200 bg-white text-gray-600 rounded-full px-3 py-1 text-[11px] font-semibold tracking-wide uppercase cursor-pointer transition-colors hover:border-gray-400',
    lensChipActive: 'inline-flex items-center gap-1.5 border border-gray-700 bg-gray-800 text-white rounded-full px-3 py-1 text-[11px] font-semibold tracking-wide uppercase cursor-pointer',
    lensCount: 'text-[10px] font-bold rounded-full px-1.5 bg-gray-100 text-gray-600',
    lensCountActive: 'text-[10px] font-bold rounded-full px-1.5 bg-amber-400 text-white',
    divider: 'w-px h-5 bg-gray-200 mx-0.5',
    filterSelect: 'text-[11px] text-gray-600 bg-white border border-gray-200 rounded px-2 py-1 pr-6 appearance-none cursor-pointer focus:outline-none focus:border-gray-400 hover:border-gray-400',
    filterSelectActive: 'text-[11px] text-gray-900 bg-indigo-50 border border-indigo-300 rounded px-2 py-1 pr-6 appearance-none cursor-pointer focus:outline-none font-semibold',
    filterWrap: 'relative',
    filterCaret: 'pointer-events-none absolute right-1.5 top-1/2 -translate-y-1/2 text-gray-400 text-[9px]',
    searchWrap: 'relative',
    searchInput: 'bg-gray-50 border border-gray-200 rounded-full text-[12px] text-gray-700 pl-7 pr-3 py-1 w-52 focus:outline-none focus:border-gray-400',
    searchIcon: 'absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none',
    scopeSeg: 'inline-flex bg-gray-50 border border-gray-200 rounded-full p-0.5',
    scopeBtn: 'border-none bg-transparent rounded-full px-3 py-0.5 text-[11px] tracking-wide uppercase text-gray-400 cursor-pointer',
    scopeBtnActive: 'border-none bg-white rounded-full px-3 py-0.5 text-[11px] tracking-wide uppercase text-gray-800 shadow-sm cursor-pointer',
    ghostBtn: 'text-[11px] font-semibold px-2.5 py-1 rounded-full border border-gray-200 bg-white text-gray-600 cursor-pointer hover:bg-gray-50 hover:border-gray-400',
    addBtn: 'text-[11px] font-semibold px-3 py-1 rounded-full bg-gray-800 text-white cursor-pointer hover:bg-gray-700 border-none',
    tableWrap: 'flex-1 min-h-0 overflow-hidden',
    loadingWrap: 'flex items-center justify-center h-32 text-gray-400 text-sm',
    footer: 'px-4 py-2 border-t border-gray-100 bg-gray-50 text-[10px] text-gray-400 font-semibold tracking-widest uppercase flex-shrink-0',
    footerInline: 'text-[10px] text-gray-400 font-semibold tracking-widest uppercase',

    // sections panel (openOut below row)
    sectionsPanel: 'w-full',
    sectionsPanelInner: 'border-l-2 border-gray-200 ml-12 my-1',
    sectionsMeta: 'flex items-center gap-2.5 px-3 py-1.5 border-b border-gray-100 text-[10px] text-gray-400 font-semibold tracking-widest uppercase flex-wrap',
    sectionsMetaCount: 'text-[11px] text-gray-400 font-normal tracking-normal',
    sectionsScroll: 'max-h-[360px] overflow-y-auto',
    sectionRow: 'grid gap-3 px-3 py-1.5 items-center text-[12px] text-gray-600 border-b border-gray-50 hover:bg-gray-50',
    sectionRowCols: '1fr 90px 200px 80px 60px 60px',
    sectionTitle: 'font-semibold text-gray-800 truncate',
    sectionDerived: 'text-gray-500 truncate',
    sectionEmpty: 'text-gray-300 italic truncate',

    // section group headers
    sectionGroupBlock: '',
    sectionGroupHeaderPublished: 'flex items-center gap-2 px-3 py-1 bg-gray-50 border-b border-gray-100 border-t border-gray-100 text-[10px] font-semibold uppercase tracking-widest text-gray-500',
    sectionGroupHeaderDraft: 'flex items-center gap-2 px-3 py-1 bg-amber-50/60 border-b border-amber-100 border-t border-amber-100 text-[10px] font-semibold uppercase tracking-widest text-amber-600',
    sectionGroupOrphanHeader: 'flex items-center gap-2 px-3 py-1 bg-red-50 border-b border-red-100 border-t border-red-100 text-[10px] font-semibold uppercase tracking-widest text-red-500',
    sectionGroupPosition: 'text-[9px] font-normal normal-case tracking-normal opacity-60',
    sectionGroupCount: 'text-[9px] font-normal normal-case tracking-normal ml-auto opacity-60',
    sectionGroupEmpty: 'px-3 py-2 text-[11px] text-gray-300 italic',
    groupBadgeDraft: 'inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold uppercase bg-amber-100 text-amber-700',
    groupBadgePublished: 'inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold uppercase bg-emerald-50 text-emerald-600 border border-emerald-200',
    sectionBadgeDraft: 'inline-flex items-center px-1 py-px rounded text-[9px] font-bold uppercase bg-amber-100 text-amber-700 ml-1 flex-shrink-0',
    sectionBadgePublished: 'inline-flex items-center px-1 py-px rounded text-[9px] font-bold uppercase bg-emerald-50 text-emerald-600 border border-emerald-200 ml-1 flex-shrink-0',
    groupRestoreBtn: 'text-[9px] font-semibold px-2 py-0.5 rounded border border-emerald-300 bg-emerald-50 text-emerald-700 cursor-pointer hover:bg-emerald-100',
    groupDeleteBtn: 'text-[9px] font-semibold px-2 py-0.5 rounded border border-red-200 bg-white text-red-600 cursor-pointer hover:bg-red-50',
    groupProcessing: 'text-[9px] text-gray-400 italic',
    badgeBase: 'inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wide',
    badgeCard: 'bg-purple-50 text-purple-700',
    badgeSpreadsheet: 'bg-blue-50 text-blue-700',
    badgeLexical: 'bg-gray-100 text-gray-600',
    badgeMap: 'bg-teal-50 text-teal-700',
    badgeHeader: 'bg-amber-50 text-amber-700',
    badgeFooter: 'bg-amber-50 text-amber-700',
    badgeGraph: 'bg-green-50 text-green-700',
    srcLabel: 'font-mono text-[11px] bg-gray-50 border border-gray-200 px-1.5 py-0.5 rounded text-gray-600 truncate',
    viewChipOk: 'font-mono text-[10px] px-1.5 py-0.5 rounded-full bg-gray-50 text-gray-400 border border-gray-200',
    viewChipStale: 'font-mono text-[10px] px-1.5 py-0.5 rounded-full bg-orange-50 text-orange-600 border border-orange-200 font-bold cursor-pointer',
    viewChipFresh: 'font-mono text-[10px] px-1.5 py-0.5 rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200 font-bold',
    levelPill: 'inline-flex items-center px-1.5 py-0.5 rounded-full text-[10px] font-semibold',
    levelHidden: 'bg-gray-100 text-gray-400',
    levelHeading: 'bg-blue-50 text-blue-700',
    publishBtn: 'text-[11px] font-semibold px-2.5 py-1 rounded-full bg-emerald-600 text-white cursor-pointer hover:bg-emerald-700 border-none',
    publishBtnDisabled: 'text-[11px] font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-400 border-none cursor-default',
    discardBtn: 'text-[11px] font-semibold px-2.5 py-1 rounded-full bg-white text-amber-700 border border-amber-300 cursor-pointer hover:bg-amber-50',
    deleteBtn: 'text-[11px] font-semibold px-2.5 py-1 rounded-full bg-white text-red-600 border border-red-200 cursor-pointer hover:bg-red-50',
    rowActions: 'flex items-center gap-1 justify-end flex-wrap',

    // delete confirmation modal
    deleteModal: 'p-6 max-w-sm w-full',
    deleteModalTitle: 'text-[15px] font-semibold text-gray-900 mb-2',
    deleteModalDesc: 'text-[13px] text-gray-600 mb-1',
    deleteModalHighlight: 'font-semibold text-gray-900',
    deleteModalWarn: 'text-[12px] text-red-600 bg-red-50 border border-red-200 rounded px-3 py-2 mb-4',
    deleteModalInfo: 'text-[12px] text-gray-500 mb-4',
    deleteModalFooter: 'flex items-center justify-end gap-2',
    deleteModalConfirmBtn: 'text-[12px] font-semibold px-3 py-1.5 rounded bg-red-600 text-white border-none cursor-pointer hover:bg-red-700',
    deleteModalCancelBtn: 'text-[12px] font-semibold px-3 py-1.5 rounded border border-gray-200 bg-white text-gray-600 cursor-pointer hover:bg-gray-50',

    // element preview modal
    previewPanel: 'relative w-full max-w-lg p-0 overflow-hidden',
    previewHeader: 'flex items-start justify-between px-5 pt-5 pb-3 border-b border-gray-100',
    previewTitle: 'font-semibold text-gray-900 text-[15px] truncate max-w-xs',
    previewMeta: 'flex items-center gap-2 mt-1 flex-wrap',
    previewBody: 'px-5 py-4 space-y-3',
    previewRow: 'flex items-center gap-2 text-[12px]',
    previewLabel: 'text-gray-400 uppercase tracking-wide text-[10px] font-semibold w-16 flex-shrink-0',
    previewValue: 'text-gray-700 truncate',
    previewFooter: 'px-5 py-3 border-t border-gray-100 flex items-center justify-end gap-3',
    previewLink: 'text-[11px] text-blue-600 hover:underline',
}
