import PatternList from './layout/patternList'

const pattern = {
  app: "dms-site",
  type: "pattern",
  attributes: [
    { key: "pattern_type",
      type: "select",
      required: true,
      default: "page",
        options: [
        {value: 'page', label: 'Page'},
        {value: 'form', label: 'Custom'}
      ],
    },
    { key: "doc_type",
      type: "text",
      required: true
    },
    { key: "base_url",
      type: "text",
      required: true
    },
    { key: "subdomain",
      type: "text",
      required: true
    },
    { key: 'theme'
      type: 'text'
    },
  ] 
}


const cmsPageFormat = {
  app: "dms-site",
  type: "pattern-admin",
  registerFormats: [pattern],
  attributes: [
    
    // if is generated by template or is template -99
    {
      key: 'site_name',
      type: "text",
      hidden: true
    },    
    //content
    {
      key: 'patterns',
      type: 'dms-format',
      isArray: true,
      format: 'dms-site+pattern',
      DisplayComp: PatternList
    },    
  ]
}



export default cmsPageFormat