import PatternList from './components/patternList'

export const themeFormat = {
  app: 'admin',
  type: 'theme',
  attributes: [
    {
      key: "name",
      type: "text"
    },
    {
      key: "theme_id",
      type: "text"
    },
    {
      key: "theme",
      type: "json",
      default: {}
    }
  ]
}

export const pattern = {
  app: "admin",
  type: "pattern",
  registerFormats: [],
  attributes: [
      // we need a type for this?
    { key: "pattern_type",
      type: "select",
      required: true,
      default: "page",
        options: [
        {value: 'auth', label: 'Auth'},
        {value: 'page', label: 'Page'},
        {value: 'forms', label: 'Forms'},
        {value: 'datasets', label: 'Datasets'}
      ],
    },
    // doc_type: uuid string to identify pattern entries in db
    { key: "name",
      placeholder: 'Name',
      type: "text",
      required: true
    },
    { key: "base_url",
      placeholder: 'Base URL',
      type: "text",
      required: true
    },
    { key: "subdomain",
      placeholder: 'Subdomain',
      type: "text",
      required: true
    },
    {
      key: "filters",
      type: "json",
      required: false,
      default: [],
    },
    {
      key: "authPermissions",
      type: "json",
      required: false,
      default: [],
        permissionDomain: [
            // some defaults to take care of in implementation:
            // if you create, you get view and edit
            // each page created gets created with default permissions (if set in pattern), and assign full access (*) to the user who created it
            {label: '*', value: '*'},
            {label: 'View Page', value: 'view-page'},
            {label: 'Create Page', value: 'create-page'},
            {label: 'Edit Page Content', value: 'edit-page'},
            {label: 'Edit Page Layout', value: 'edit-page-layout'},
            {label: 'Edit Page Params', value: 'edit-page-params'},
            {label: 'Edit Page Permissions', value: 'edit-page-permissions'},
            {label: 'Publish Page', value: 'publish-page'},
        ]
    },
    { key: 'config',
      placeholder: 'please select a type',
      type: 'config'
    },
    { key: "description",
      placeholder: 'Description',
      type: "lexical",
      required: true
    },
    { key: "categories",
      placeholder: 'Categories',
      type: "text",
      required: true
    },
    { key: 'theme',
      placeholder: '',
      type: 'config'
    }
  ]
}

const patternAdminFormat = {
  app: "admin",
  type: "pattern-admin",
  registerFormats: [pattern, themeFormat],
  attributes: [

    // if is generated by template or is template -99
    {
      key: 'site_name',
      placeholder: 'Site Name',
      type: "text",
      hidden: true
    },
    //content
    {
      key: 'patterns',
      type: 'dms-format',
      isArray: true,
      format: 'admin+pattern',
      DisplayComp: PatternList
    },
    {
      key: 'themes',
      type: 'json'
    },
    {
      key: 'theme_refs',
      type: 'dms-format',
      isArray: true,
      format: 'admin+theme'
    }
  ]
}



export default patternAdminFormat
