export const pageTemplateManagerTheme = {
  wrapper: 'p-6',
  error: 'text-sm text-red-500 mb-4',
  sectionTitle: 'text-sm font-semibold text-gray-700 mb-2 pb-1 border-b border-gray-100',
  sectionTitleSpaced: 'text-sm font-semibold text-gray-700 mb-2 pb-1 border-b border-gray-100 mt-6',
  sectionCount: 'ml-1 font-normal text-gray-400',
  table: 'w-full text-sm mb-2',
  thead: 'border-b',
  th: 'pb-2 pr-4 text-left text-gray-500 text-xs uppercase tracking-wider font-medium',
  thLast: 'pb-2 text-left text-gray-500 text-xs uppercase tracking-wider font-medium',
  tr: 'border-b hover:bg-gray-50',
  tdName: 'py-2 pr-4 font-medium text-gray-900',
  tdDesc: 'py-2 pr-4 text-gray-500',
  tdMeta: 'py-2 pr-4 text-gray-400 text-xs',
  tdActions: 'py-2 whitespace-nowrap',
  copyBtn: 'text-blue-500 cursor-pointer hover:text-blue-700 text-xs',
  confirmRow: 'flex gap-2 items-center text-xs',
  confirmLabel: 'text-gray-500',
  confirmYes: 'text-red-500 cursor-pointer hover:underline',
  confirmNo: 'text-gray-400 cursor-pointer hover:underline',
  deleteBtn: 'text-red-400 cursor-pointer hover:text-red-600 text-xs',
  newForm: 'mb-4',
  newFormFields: 'flex flex-wrap gap-2 items-end',
  newFormHint: 'text-xs text-gray-400 mt-1',
  baseSelect: 'border border-gray-200 rounded px-2 py-1 text-sm text-gray-700 bg-white',
  empty: 'text-sm text-gray-400 py-6 text-center',
};
