export const pageTemplatePickerTheme = {
  backdrop: 'fixed inset-0 bg-black/60 z-50 flex items-center justify-center',
  modal: 'bg-white rounded-xl shadow-xl w-[700px] max-h-[80vh] flex flex-col',
  header: 'flex items-center justify-between px-6 py-4 border-b border-gray-100',
  headerTitle: 'text-base font-semibold text-gray-900',
  tabs: 'flex gap-1 px-6 pt-3',
  tab: 'px-3 py-1 rounded-full text-sm cursor-pointer text-gray-500 hover:text-gray-700 hover:bg-gray-50',
  tabActive: 'px-3 py-1 rounded-full text-sm cursor-pointer bg-gray-100 text-gray-900 font-medium',
  grid: 'grid grid-cols-3 gap-3 p-6 overflow-y-auto flex-1',
  card: 'border border-gray-200 rounded-lg p-3 cursor-pointer hover:border-blue-400 hover:shadow-sm transition-all flex flex-col',
  cardSelected: 'border-2 border-blue-500 rounded-lg p-3 cursor-pointer shadow-sm bg-blue-50 flex flex-col',
  cardPreview: 'w-full h-16 rounded bg-gray-50 border border-gray-100 flex flex-col gap-1 p-1.5 overflow-hidden mb-2',
  cardPreviewBlock: 'rounded bg-gray-300',
  cardName: 'font-medium text-gray-900 text-sm',
  cardDescription: 'text-xs text-gray-400 mt-0.5',
  footer: 'flex justify-between items-center px-6 py-4 border-t border-gray-100',
  footerInfo: 'text-sm text-gray-500',
  footerActions: 'flex gap-2',
  cancelBtn: 'px-4 py-2 rounded-lg border border-gray-200 text-sm cursor-pointer hover:bg-gray-50 text-gray-700',
  createBtn: 'px-4 py-2 rounded-lg bg-blue-500 text-white text-sm cursor-pointer hover:bg-blue-600',
  createBtnDisabled: 'px-4 py-2 rounded-lg bg-blue-200 text-white text-sm cursor-not-allowed',
  emptyState: 'col-span-3 text-center py-10 text-gray-400 text-sm',
  loadingState: 'col-span-3 text-center py-10 text-gray-400 text-sm',
};
