export const patternPickerTheme = {
  grid: 'grid grid-cols-3 gap-2 p-4',
  optCard: 'relative border border-slate-200 rounded-lg p-3 cursor-pointer select-none bg-slate-50 hover:border-slate-400 hover:bg-white transition-colors',
  optCardSelected: 'relative border-2 border-slate-700 rounded-lg p-3 cursor-pointer select-none bg-white ring-2 ring-slate-200',
  optName: 'text-sm font-semibold text-slate-700',
  optDesc: 'text-xs text-slate-400 mt-1 leading-snug',
  pageTag: 'absolute top-2 right-2 text-[9px] font-semibold uppercase tracking-wider bg-slate-100 text-slate-400 px-1.5 py-0.5 rounded',
  pageTagSelected: 'absolute top-2 right-2 text-[9px] font-semibold uppercase tracking-wider bg-slate-200 text-slate-500 px-1.5 py-0.5 rounded',
  dividerRow: 'col-span-3 flex items-center gap-2 py-1',
  dividerLine: 'flex-1 h-px bg-slate-200',
  dividerLabel: 'text-[9px] font-semibold uppercase tracking-widest text-slate-300 whitespace-nowrap',
  confirmArea: 'border-t border-slate-200 px-4 py-3',
  confirmLabel: 'text-[11px] font-semibold uppercase tracking-wide text-slate-400 mb-2',
  confirmFields: 'flex gap-2 items-end',
  confirmField: 'flex flex-col gap-1 flex-1',
  urlField: 'flex flex-col gap-1 max-w-[160px]',
  fieldLabel: 'text-xs font-semibold text-slate-500',
  fieldInput: 'border border-slate-200 rounded-md px-2.5 py-1.5 text-sm text-slate-700 w-full outline-none focus:border-slate-500 bg-white',
  emptyArea: 'border-t border-slate-200 px-4 py-3 text-center text-sm text-slate-300 italic',
  btnAdd: 'shrink-0 bg-slate-700 hover:bg-slate-900 text-white text-sm font-semibold px-4 py-1.5 rounded-md disabled:opacity-40',
}
